version: '3.2'

services:
  traefik:
    build: .
    command: --logLevel=DEBUG
    environment:
      GODADDY_API_KEY: "${GODADDY_API_KEY}"
      GODADDY_API_SECRET: "${GODADDY_API_SECRET}"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverseproxy
    cap_drop:
      - all
    cap_add:
      - net_bind_service

networks:
  reverseproxy:
    driver: bridge
