version: '3.2'

services:
  traefik:
    build: .
    command: --logLevel=DEBUG
    restart: always
    networks:
      - default
      - reverseproxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      GODADDY_API_KEY: "${GODADDY_API_KEY}"
      GODADDY_API_SECRET: "${GODADDY_API_SECRET}"
    labels:
      - "traefik.enable=true" 
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.mwcm.ca"
      - "traefik.port=8080"
      - "traefik.docker.network=reverseproxy_reverseproxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker/traefik:/etc/traefik
    cap_drop:
      - all
    cap_add:
      - net_bind_service
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker/portainer/data:/data
      - /root/docker/shared:/shared
    environment:
      - TZ="America/New_York"
    networks:
      - reverseproxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.mwcm.ca"  
      - "traefik.port=9000"
      - "traefik.docker.network=reverseproxy_reverseproxy"

networks:
  reverseproxy:
    driver: bridge
