version: '3.2'

services:
  reverseproxy:
    hostname: reverseproxy
    container_name: reverseproxy
    build: .
    command: --logLevel=DEBUG
    restart: always
    networks:
      - default
      - reverseproxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      GODADDY_API_KEY: "${GODADDY_API_KEY}"
      GODADDY_API_SECRET: "${GODADDY_API_SECRET}"
    labels:
      - "traefik.enable=true" 
      - "traefik.backend=reverseproxy"
      - "traefik.frontend.rule=Host:traefik.mwcm.ca"
      - "traefik.port=8080"
      - "traefik.docker.network=reverseproxy_reverseproxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker/traefik:/etc/traefik
    cap_drop:
      - all
    cap_add:
      - net_bind_service

networks:
  reverseproxy:
    driver: bridge
